// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UnCRM.Api.Data;

#nullable disable

namespace UnCRM.Api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250514141717_CriarTabelasProjeto")]
    partial class CriarTabelasProjeto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UnCRM.Api.Domain.Models.Atendimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("timestamp");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.Property<long>("TipoAtendimentoId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioCriacaoId")
                        .HasColumnType("BIGINT");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TipoAtendimentoId");

                    b.ToTable("atendimento", (string)null);
                });

            modelBuilder.Entity("UnCRM.Api.Domain.Models.Parecer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtendimentoId")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR");

                    b.Property<long>("UsuarioCriacaoId")
                        .HasColumnType("BIGINT");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.ToTable("parecer", (string)null);
                });

            modelBuilder.Entity("UnCRM.Api.Domain.Models.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("timestamp");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("NomeCurto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("pessoa", (string)null);
                });

            modelBuilder.Entity("UnCRM.Api.Domain.Models.TipoAtendimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("tipo_atendimento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "Renovação de Contrato"
                        },
                        new
                        {
                            Id = 2L,
                            Descricao = "Atualização de Sistema"
                        },
                        new
                        {
                            Id = 3L,
                            Descricao = "Dúvida sobre o sistema"
                        },
                        new
                        {
                            Id = 4L,
                            Descricao = "Erro de Sistema"
                        },
                        new
                        {
                            Id = 5L,
                            Descricao = "Reclamação"
                        },
                        new
                        {
                            Id = 6L,
                            Descricao = "Cancelamento"
                        });
                });

            modelBuilder.Entity("UnCRM.Api.Domain.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("timestamp");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("UnCRM.Api.Domain.Models.Atendimento", b =>
                {
                    b.HasOne("UnCRM.Api.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnCRM.Api.Domain.Models.TipoAtendimento", "TipoAtendimento")
                        .WithMany()
                        .HasForeignKey("TipoAtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UnCRM.Api.Domain.Models.DadosProximoContato", "ProximoContato", b1 =>
                        {
                            b1.Property<long>("AtendimentoId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("Data")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DataProximoContato");

                            b1.Property<long>("Usuario")
                                .HasColumnType("bigint")
                                .HasColumnName("UsuarioProximoContato");

                            b1.HasKey("AtendimentoId");

                            b1.ToTable("atendimento");

                            b1.WithOwner()
                                .HasForeignKey("AtendimentoId");
                        });

                    b.Navigation("Pessoa");

                    b.Navigation("ProximoContato");

                    b.Navigation("TipoAtendimento");
                });

            modelBuilder.Entity("UnCRM.Api.Domain.Models.Parecer", b =>
                {
                    b.HasOne("UnCRM.Api.Domain.Models.Atendimento", "Atendimento")
                        .WithMany("Pareceres")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("UnCRM.Api.Domain.Models.Atendimento", b =>
                {
                    b.Navigation("Pareceres");
                });
#pragma warning restore 612, 618
        }
    }
}
