export const icons = {
    menu: 'mdi-menu',
    paginaInicial: 'mdi-home-outline',
    atendimento: 'mdi-newspaper-variant-outline', 
    usuario: 'mdi-account-group-outline',
    pessoa: 'mdi-card-account-details-outline',
    alternarTema: 'mdi-theme-light-dark',
    logout: 'mdi-logout',
    adicionar: 'mdi-plus',
    filtro: 'mdi-filter-variant',
    subMenu: 'mdi-dots-vertical',
    historico: 'mdi-file-eye-outline', 
    alterarProximoContato: 'mdi-calendar-edit-outline',
    tipoAtendimento: 'mdi-tag-outline',
    inativar: 'mdi-account-off-outline',
    editar: 'mdi-pencil-outline',
    dataGenerico: 'mdi-calendar-blank-outline',
    usuarioGenerico: 'mdi-account',
    registrarParecer: 'mdi-send-variant-outline',
    status: 'mdi-progress-helper',
    reabrir: 'mdi-restore',
    codigoAtendimento: 'mdi-information-slab-circle-outline'
}